dev:
  OKTA_CLIENTID: {ClientId}
  OKTA_CLIENTSECRET: {ClientSecret}
  OKTA_DOMAIN: {OktaIssuer}
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: {NextAuthSecret}
  CHAT_API_URL: {ChatApiUrl}
  CHAT_API_KEY: {ChatApiKey}
  USER_API_URL: {UserApiUrl}
  OKTA_LOGIN: Disable
prod:
  OKTA_CLIENTID: {ClientId}
  OKTA_CLIENTSECRET: {ClientSecret}
  OKTA_DOMAIN: {OktaIssuer}
  NEXTAUTH_URL: {NextAuthUrl}
  NEXTAUTH_SECRET: {NextAuthSecret}
  CHAT_API_URL: {ChatApiUrl}
  CHAT_API_KEY: {ChatApiKey}
  USER_API_URL: {UserApiUrl}
  OKTA_LOGIN: Disable
